version: '3'
services:
  pgdb_news_list:
    image: 'postgres:alpine'
    ports:
      - '5432:5432'
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD='${DB_PASSWORD}'
      - POSTGRES_USER='${DB_USERNAME}'
      - POSTGRES_DB='${DB_DATABASE}'
    volumes:
      - 'newslistdata:/var/lib/postgresql'
    networks:
      - news-list
volumes:
  newslistdata:
    driver: local
networks:
  news-list:
    driver: bridge
    ipam:
      driver: default
